image:
  repository: docker.io/antonbootstraplabs/openems-edge
  pullPolicy: IfNotPresent
  tag: armv8

service:
  name: openems
  type: ClusterIP

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 200M
release:
  namespace: openems
