{{- if .Values.persistence.enabled  }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.service.name }}-edge-conf-pvc
  namespace: {{ .Values.release.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.service.name }}-edge-data-pvc
  namespace: {{ .Values.release.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}

  {{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: {{ .Values.release.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M



